[package]
name = "econtroller"
version = "0.1.0"
edition = "2024"

[dependencies]
webots = { path = "../webots-rs" }
interfaces = { path = "../interfaces" }
zenoh = "1.3.4"
prost = "0.13.5"
env_logger = "0.11.8"
tokio = "1.45.0"
log = "0.4.27"
