[package]
name = "heronc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
webots = { path = "../webots-rs" }
hiroz = { git = "https://github.com/ZettaScaleLabs/hiroz.git"}
hiroz-msgs = { git = "https://github.com/ZettaScaleLabs/hiroz.git" }
prost = "0.14.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.48.0", features = ["full"] }
chrono = "0.4.42"
anyhow = "1.0.102"
